// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOihH7BzfyWYkdaZspZoVANaSGQqKbpSE',
    appId: '1:536569981833:web:774e19cd5f976bc2fa4f58',
    messagingSenderId: '536569981833',
    projectId: 'mybudget-7ceaa',
    authDomain: 'mybudget-7ceaa.firebaseapp.com',
    databaseURL: 'https://mybudget-7ceaa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mybudget-7ceaa.appspot.com',
    measurementId: 'G-J4MK8LJ90Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkvbJ2ffjrnW_pUHP74C-2Y0A9x01Zuwk',
    appId: '1:536569981833:android:80f264af38ac6f42fa4f58',
    messagingSenderId: '536569981833',
    projectId: 'mybudget-7ceaa',
    databaseURL: 'https://mybudget-7ceaa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mybudget-7ceaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWyBgo5Vjhb1BnkN6u2ZtBSbOSz6PUwH4',
    appId: '1:536569981833:ios:04b042b239664d6dfa4f58',
    messagingSenderId: '536569981833',
    projectId: 'mybudget-7ceaa',
    databaseURL: 'https://mybudget-7ceaa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mybudget-7ceaa.appspot.com',
    iosBundleId: 'com.example.myBudget',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWyBgo5Vjhb1BnkN6u2ZtBSbOSz6PUwH4',
    appId: '1:536569981833:ios:c859b87cf86860d2fa4f58',
    messagingSenderId: '536569981833',
    projectId: 'mybudget-7ceaa',
    databaseURL: 'https://mybudget-7ceaa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mybudget-7ceaa.appspot.com',
    iosBundleId: 'com.example.myBudget.RunnerTests',
  );
}
